[dev]
  command = "npm run dev"
  publish = "dist"
  # We need another port for the application because Vite occupies the 3000.
  port = 8080

[build]
  command = "npm run vite:build"
  publish = "dist/"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# We have to tell the Netlify that this URL will be served by the books.js function.
[[redirects]]
  from = "/api/azureApi"
  to = "/.netlify/functions/azureApi"
  status = 200